#!/bin/bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== Hook docs requirements =="
python3 - <<'PY' "$REPO_ROOT"
import sys
from pathlib import Path

repo = Path(sys.argv[1])

docs = {
    repo / "README.md": [
        "**macOS / Linux requirements:** bash, python3, and jq",
        "installer uses python3 to manage",
        "safety-check uses python3",
        "most standalone shell hooks use jq",
        "Install boundary: these commands download `tools/install.sh` or `tools/install.ps1` from GitHub raw content",
        "Installing adds managed hook files under `~/.claude/hooks` and updates `~/.claude/settings.json`",
        "The installer does not upload your settings, hook files, shell history, repository contents, or safety summary output",
        "Install boundary: this downloads `tools/enforce/install.sh` and",
        "`tools/enforce/enforce-hooks.py` from GitHub raw content",
        "It may create `CLAUDE.md`, install",
        "update project `.claude/settings.json`",
        "`CLAUDE.md`, settings, hook files, shell history, repository contents, or audit",
        "No hook installation required for the audit",
        "Audit boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "--verify --summary-only",
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --strict",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --summary-only",
        'if ($root) { Set-Location $root }',
        "representative hook payloads to each hook",
        "does not execute the dangerous shell or git commands",
        "**Windows (PowerShell 7+)",
        "tools/install.ps1) } recommended",
        "Or install all standalone hooks at once",
        "Project hooks skipped from subdirectories",
        "ancestor project settings warning",
        "If you use `claude -w`, also install [worktree-guard]",
        "delete unmerged or unpushed commits",
        "That path downloads `check.sh` from GitHub raw content",
        "uploads no settings, hook files, shell history, repository contents, or summary output",
        "tools/install.sh | bash -s -- backup list",
        "tools/install.sh | bash -s -- restore settings.20260101_120000.json",
        "Restore the most recent backup only if you meant it",
        "Run management commands from the same project root where you start Claude Code",
        "That keeps project `.claude/settings.json` hooks visible to `verify`, `check`, and `doctor`",
        "cd \"$repo_root\" # See what's installed curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- list",
        "tools/install.sh | bash -s -- check",
        "tools/install.sh | bash -s -- check --verify --summary-only",
        "tools/install.sh | bash -s -- check --verify --strict",
        "tools/install.sh | bash -s -- recommended curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "tools/install.sh | bash -s -- all curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "tools/install.ps1) } all\" iex \"& { $(irm https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.ps1) } verify",
        "tools/install.ps1) } backup list",
        "tools/install.ps1) } restore settings.20260101_120000.json",
        "use bare `restore` only when the most recent backup is the exact snapshot you want",
        "start a fresh Claude Code session from that same project root",
        "existing session may have loaded the previous settings or hook files",
        "Test all installed hooks with representative payloads",
        "This is not a sandbox: verify the hook, start a fresh session, and review the known limitations",
        "This is read-only for the audited Claude Code session after the hook is installed",
        "Setting up the boundary intentionally edits project files first",
        "Use a disposable branch or worktree when the main checkout must stay untouched",
    ],
    repo / "tools" / "README.md": [
        "**macOS / Linux:** bash, python3, and jq",
        "installers use python3 to manage",
        "safety-check uses python3",
        "6 of the 7 standalone shell hooks use jq",
        "Install boundary: these commands download `tools/install.sh` or `tools/install.ps1` from GitHub raw content",
        "Installing adds managed hook files under `~/.claude/hooks` and updates `~/.claude/settings.json`",
        "The installer does not upload your settings, hook files, shell history, repository contents, or safety summary output",
        "Install boundary: this downloads `tools/enforce/install.sh` and",
        "`tools/enforce/enforce-hooks.py` from GitHub raw content",
        "It may create `CLAUDE.md`, install",
        "update project `.claude/settings.json`",
        "`CLAUDE.md`, settings, hook files, shell history, repository contents, or audit",
        "**Windows:** [PowerShell 7+]",
        "Git Bash or WSL for safety-check",
        "tools/install.ps1) } recommended",
        "To choose hooks interactively instead",
        "stderr` and exit code 2",
        'JSON `permissionDecision: "deny"`',
        "not a universal hard-block contract",
        "Ancestor project settings warning",
        "subdirectory launches can skip root project hooks",
        "root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "Run `verify`, `check`, and `doctor` from the same project root where you start Claude Code",
        "safety-check and root-sensitive hook tests need the same working directory as the Claude Code session",
        'if ($root) { Set-Location $root }',
        "--- End Safety Summary ---",
        "safety-check --verify --summary-only",
        "tools/install.sh | bash curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "tools/install.sh | bash -s -- recommended curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "tools/install.sh | bash -s -- read-once git-safe file-guard curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "Test installed hooks with representative payloads",
    ],
    repo / "tools" / "enforce" / "README.md": [
        "Install boundary: this downloads `tools/enforce/install.sh` and",
        "`tools/enforce/enforce-hooks.py` from GitHub raw content",
        "It may create `CLAUDE.md`, install",
        "update project `.claude/settings.json`",
        "`CLAUDE.md`, settings, hook files, shell history, repository contents, or audit",
        "PreToolUse boundaries for covered tool calls",
        "hard-block covered tool calls at the runtime level",
        "This is not a sandbox: verify the hook, start a fresh session, and review known limitations",
        "This is read-only for the audited Claude Code session after the hook is installed",
        "Setting up the boundary intentionally edits project files first",
        "Use a disposable branch or worktree when the main checkout must stay untouched",
        "deterministic boundary for those covered Write/Edit/Bash operations",
    ],
    repo / "tools" / "enforce" / "READ_ONLY_AUDIT.md": [
        "Run the safety check from the same project root",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --strict",
    ],
    repo / "tools" / "safety-check" / "README.md": [
        "No hook installation required for the audit",
        "## Requirements",
        "Audit boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "Bash 3.2+",
        "default `/bin/bash` on macOS is enough",
        "Python 3 (for JSON parsing of settings.json)",
        "The letter grade is an inventory score",
        "The trust boundary comes from the",
        "Grade C with `Verify: 0 FAIL-OPEN`",
        "Do not chase an A by reinstalling hooks",
        "Use `--verify` to send representative test payloads",
        "Hook Verification (sending representative test payloads)",
        "encoded as hook input",
        "It does not execute the shell or git commands",
        "install.sh | bash -s -- doctor",
        "install.sh | bash -s -- recommended",
        "install.ps1) } doctor",
        "install.ps1) } recommended",
        "backup_stamp=\"$(date +%Y%m%d_%H%M%S)\"",
        ".claude/settings.json.<timestamp>.bak",
        "git rev-parse --show-toplevel",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --summary-only",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --strict",
        'if ($root) { Set-Location $root }',
        "Use `all` instead of `recommended` only when you want the full standalone hook",
        "--verify --summary-only",
        "cd \"$repo_root\" unset IS_DEMO CLAUDE_CODE_SIMPLE",
        "safety summary triage guide",
        "team handoff report",
    ],
    repo / "tools" / "safety-check" / "TRIAGE.md": [
        "## Full-report warning map",
        "Some warnings appear in the full `safety-check --verify` report but not in the",
        "compact copy/paste summary",
        "`ANTHROPIC_API_KEY is set`",
        "billing-sensitive API keys are unset",
        "`GIT_INDEX_FILE is set`",
        "plugin initialization cannot write through a hook-provided index file",
        "`Sandbox mode enabled`",
        "Do not rely on repeated approval prompts for sensitive commands",
        "`Skills/workflows can override CLAUDE.md directives`",
        "Move must-enforce rules from prompt text into hooks",
        "`Running non-interactively`",
        "usage-limit prompts can hang when no terminal can answer",
        "`Your global settings.json contains keys`",
        "Back up `~/.claude/settings.json` before plugin install",
        "`Background agents spawned via the Agent tool`",
        "monitor token and process usage outside Claude Code",
        "`Project-scoped plugins detected`",
        "remove project plugins that should not run outside their declared project",
        "`MCP tools in your permission allow list`",
        "parameter value triggered stricter matching before widening allow rules",
    ],
    repo / "tools" / "safety-check" / "CI.md": [
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "cd \"$repo_root\"",
        "The fallback above moves to the git root when there is one and otherwise stays",
        "working-directory: ${{ github.workspace }}",
        "test -f .claude/settings.json",
        "tmp_home=\"$(mktemp -d)\"",
        "HOME=\"$tmp_home\" bash /tmp/safety-check.sh --verify --strict",
        "global Claude Code settings on self-hosted runners",
        "Drop the temporary `HOME` only when the job is intentionally testing hooks",
        "downloads `tools/safety-check/check.sh` from GitHub raw content",
        "runs it locally on the checked-out repository and CI user's home directory",
        "does not upload `settings.json`, hook files, shell history, repository contents, or safety summary output",
        "Treat CI logs as the only publication surface",
        "Run it from the project root that contains `.claude/settings.json`",
        "does not execute the dangerous shell or git commands",
        "run `safety-check --verify --strict` on a runner that has both `bash` and `pwsh`",
        "Do not use `install.ps1 verify` as proof for repo-local hooks",
        "installed under the CI user's `~/.claude` directory",
        "not a repo-local CI contract",
    ],
    repo / "tools" / "safety-check" / "check.sh": [
        "No hook installation required for the audit",
        "Requires bash and python3",
        "sending representative test payloads",
    ],
    repo / "tools" / "safety-check" / "SUPPORT_EVIDENCE.md": [
        "Command boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "Do not paste raw hook stderr from a live Claude Code session",
        "prefix hook stderr with the hook command path",
        "safety-check summary is the safer public artifact",
        "Build a minimal reproduction in a temporary directory",
        "smallest redacted settings file that reproduces the issue",
        "git rev-parse --show-toplevel",
        'if ($root) { Set-Location $root }',
        "--summary-only",
        "Pre-update baseline: summary/version captured / not captured / not an update issue",
        "first verified result for an already-untrusted setup",
        "--- End Safety Summary ---",
    ],
    repo / "tools" / "safety-check" / "SUPPORT_EXAMPLES.md": [
        "downloads `tools/safety-check/check.sh` from GitHub raw content",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "FAIL-OPEN public report",
        "Hook source: framework git-safe hook, not custom",
        "Verify: 1 FAIL-OPEN | 6 payload checks | 0 skipped",
        "Boundary: fix FAIL-OPEN hooks before trusting the hook layer.",
        "Do not paste raw hook stderr from the Claude Code session.",
        "temporary directory with throwaway hook paths",
        "Pre-update baseline: summary/version captured",
        "both the old Claude Code version and the bounded safety summary",
        "If only one was captured, say `not captured`",
    ],
    repo / "tools" / "safety-check" / "QUICKSTART.md": [
        "## 0. Choose the path",
        "You have never run safety-check on this machine",
        "minimal personal workstation baseline",
        "proof before a risky session, CI job, or team handoff",
        "preparing a public support request",
        "Bash 3.2+",
        "default `/bin/bash` on macOS is enough",
        "Command boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "Do not paste raw hook stderr from a live Claude Code session",
        "platform can prefix it with the hook command path",
        "safe support evidence guide",
        "--verify --summary-only",
        "--- End Safety Summary ---",
        "install user-level hooks under",
        "register them in `~/.claude/settings.json`",
        "do not create repo-local `.claude/settings.json` policy",
        "project settings when they already exist",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- recommended curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- all curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "The installer verifier sends representative payloads to the installed hooks",
        "does not execute the dangerous shell or git commands",
        "temporary-directory reproduction instead of real workspace",
        "team handoff report",
        "Pre-update baseline: summary/version captured / not captured / not an update issue",
        "first verified result for an already-untrusted setup",
        "restore the named pre-trial snapshot",
        "git rev-parse --show-toplevel",
        'if ($root) { Set-Location $root }',
        "tools/install.sh | bash -s -- backup list",
        "tools/install.sh | bash -s -- restore settings.20260101_120000.json",
        "Use bare `restore` only when the most recent backup is the exact snapshot you want back",
        "tools/install.ps1) } backup list",
        "tools/install.ps1) } restore settings.20260101_120000.json",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --strict",
        "cd \"$repo_root\" curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --summary-only",
        "cd \"$repo_root\" unset IS_DEMO CLAUDE_CODE_SIMPLE",
    ],
    repo / "tools" / "safety-check" / "FIRST_TEST.md": [
        "temporary `HOME`",
        "temporary project",
        "## Network and upload boundary",
        "Bash 3.2+ is enough for this isolated test",
        "default `/bin/bash` on macOS",
        "downloads `tools/safety-check/check.sh` from this repository through",
        "It does not upload your",
        "Claude Code settings, hook files, shell history, repository contents, or summary",
        "If your environment blocks `curl` to GitHub raw content",
        "does not install hooks",
        "does not prove your real Claude Code setup is safe",
        "HOME=\"$tmp_home\" bash -s -- --verify --summary-only",
        "Temporary paths are printed only in that keep-for-inspection mode.",
        "Verify: not run | no hooks found | 0 payload checks",
        "Boundary: install hooks before trusting the hook layer.",
        "Verification mode does not execute dangerous shell or git commands.",
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- recommended",
        "tools/install.ps1) } recommended",
        "See the [quickstart](QUICKSTART.md)",
    ],
    repo / "tools" / "enforce" / "READ_ONLY_AUDIT.md": [
        "This is read-only for the audited Claude Code session after the hook is installed",
        "Setting up the boundary intentionally edits project files first",
        "do the setup on a disposable branch or worktree",
        "Outside git, they keep you in the current project directory",
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "cd \"$repo_root\"",
        "backup_stamp=\"$(date +%Y%m%d_%H%M%S)\"",
        "cp -p .claude/settings.json \".claude/settings.json.read-only-${backup_stamp}.bak\"",
        "ls -1t .claude/settings.json.read-only-*.bak",
        "cp -p .claude/settings.json.read-only-20260101_120000.bak .claude/settings.json",
        "snapshots the project-level `.claude/settings.json` before",
        "timestamp keeps repeated audit setup",
        "If there was no pre-audit settings file",
        "remove only the temporary enforce hook entry and generated plugin files",
        "endswith(\"enforce-pretooluse.sh\")",
        "rmdir .claude/hooks .claude",
        "remove the `enforce-pretooluse.sh` hook from Claude Code's",
        "Expect the strict audit to exit non-zero",
        "policy is no longer covered by",
        "zero `FAIL-OPEN` results for any remaining hooks",
        "start a fresh Claude Code session from that same project root",
        "old in-memory boundary",
    ],
    repo / "tools" / "safety-check" / "UPDATE_CHECKLIST.md": [
        "same project root you use to start Claude Code",
        "git rev-parse --show-toplevel",
        'if ($root) { Set-Location $root }',
        "before changing anything from",
        "Capture the current version and bounded summary before changing anything",
        "Command boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "backup_stamp=\"$(date +%Y%m%d_%H%M%S)\"",
        "$stamp = Get-Date -Format yyyyMMdd_HHmmss",
        "cp .claude/settings.json.20260101_120000.bak .claude/settings.json",
        "Copy-Item .claude/settings.json.20260101_120000.bak .claude/settings.json",
        "claude --version 2>/dev/null",
        "--verify --summary-only",
        "record the Claude Code version and the native verifier count",
        "Then verify the updated hook boundary",
        "Compare the new version and verification result with the pre-update notes",
        "Pre-update baseline: summary/version captured / not captured / not an update issue",
        "first verified result for an already-untrusted setup",
    ],
    repo / "tools" / "safety-check" / "TEAM_HANDOFF.md": [
        "Use this when one person has verified a Claude Code hook boundary",
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"",
        "--verify --summary-only",
        "Command boundary: this downloads `tools/safety-check/check.sh` from GitHub raw",
        "runs it locally on your current project and Claude Code settings",
        "does not upload your `settings.json`, hook files, shell history, repository contents, session logs, or safety summary output",
        "Fresh Claude Code session started after verification",
        "Residual platform warnings",
        "Next recheck trigger",
        "Treat this as a boundary statement, not a certificate.",
        "For native Windows `install.ps1 verify`, replace the safety summary block",
        "temporary reproduction",
        "For public support threads, use the [safe support evidence guide]",
    ],
    repo / "docs" / "index.html": [
        "bash, python3, and jq",
        "No hook installation required for the audit",
        "Audit boundary: this downloads <code>tools/safety-check/check.sh</code> from GitHub raw content",
        "runs it locally on your current project and Claude Code settings",
        "does not upload <code>settings.json</code>, hook files, shell history, repository contents, session logs, or safety summary output",
        "Install boundary: these commands download <code>tools/install.sh</code> or <code>tools/install.ps1</code> from GitHub raw content",
        "Installing adds managed hook files under <code>~/.claude/hooks</code> and updates <code>~/.claude/settings.json</code>",
        "The installer does not upload your settings, hook files, shell history, repository contents, or safety summary output",
        "Install boundary: this downloads <code>tools/enforce/install.sh</code> and <code>tools/enforce/enforce-hooks.py</code> from GitHub raw content",
        "It may create <code>CLAUDE.md</code>, install <code>.claude/hooks/enforce-hooks.py</code>",
        "update project <code>.claude/settings.json</code>",
        "It does not upload <code>CLAUDE.md</code>, settings, hook files, shell history, repository contents, or audit output",
        "repo_root=\"$(git rev-parse --show-toplevel 2&gt;/dev/null || pwd)\"",
        "install.ps1) } recommended",
        "install the same recommended set from PowerShell 7",
        "start a fresh Claude Code session from that same project root",
        "github.com/anthropics/claude-code/issues/37550",
        "Safety-check invokes the hook scripts with Claude-style JSON input",
        "does not execute the dangerous shell or git commands",
        "Read the strict result as boundary evidence, not as a badge",
        "Use <code>backup list</code> first, then restore the named backup you intend to use",
        "Verify: not run",
        "0 payload checks",
        "FAIL-OPEN",
        "skipped <code>PreToolUse</code>",
        "Verify: 0 FAIL-OPEN",
        "instead of reinstalling repeatedly to chase an A",
        "safety summary triage guide",
        "200+ Rust tests",
        "tools/safety-check/FIRST_TEST.md",
        "First Test",
        "tools/safety-check/QUICKSTART.md",
        "Quickstart",
        "tools/enforce/READ_ONLY_AUDIT.md",
        "Read-only Audit",
        "tools/safety-check/SUPPORT_EVIDENCE.md",
        "Safe Support Evidence",
        "tools/safety-check/SUPPORT_EXAMPLES.md",
        "Safe Support Examples",
        "copy what is safe to share",
        "tools/safety-check/TRIAGE.md",
        "Safety Summary Triage",
        "tools/safety-check/TEAM_HANDOFF.md",
        "Team Handoff",
        "application/atom+xml",
        "Claude Code Hook Limitations Feed",
        "/limitations-feed.xml",
        "application/json",
        "Claude Code Hook Limitations JSON",
        "/limitations.json",
        "limitations-feed.xml",
        "Limitations Feed",
        "Atom updates",
        "limitations.json",
        "Limitations JSON",
        "machine-readable export",
        "llms.txt",
        "LLM Summary",
        "compact machine-readable guide",
        "tools/install.sh | bash -s -- recommended <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "tools/install.sh | bash -s -- all <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "cd \"$repo_root\" <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash -s -- --verify --strict",
        "cd \"$repo_root\" <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- check --verify --summary-only",
        "cd \"$repo_root\" <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- backup",
        "cd \"$repo_root\" <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash</code>",
    ],
    repo / "docs" / "sitemap.xml": [
        "https://framework.boucle.sh/",
        "https://framework.boucle.sh/recipes.html",
        "https://framework.boucle.sh/limitations.html",
        "https://framework.boucle.sh/llms.txt",
        "https://framework.boucle.sh/limitations.json",
        "https://framework.boucle.sh/limitations-feed.xml",
    ],
    repo / "docs" / "llms.txt": [
        "Boucle Framework is a public, open-source project for Claude Code safety hooks",
        "Try safety-check without reading real Claude Code settings",
        "Bash 3.2+",
        "default `/bin/bash` on macOS works",
        "tmp_home=\"$(mktemp -d)\"",
        "tmp_project=\"$(mktemp -d)\"",
        "cleanup()",
        "KEEP_BOUCLE_FIRST_TEST",
        "Temporary directories were not empty; inspect and remove manually",
        "trap cleanup EXIT",
        "cd \"$tmp_project\"",
        "Audit a Claude Code setup from the project root",
        "repo_root=\"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\"; cd \"$repo_root\"",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/safety-check/check.sh | bash",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- recommended",
        "curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "Ask for public support with a bounded summary from the project root",
        "iex \"& { $(irm https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.ps1) } recommended\"",
        "Safety-check audit mode does not install hooks.",
        "The hook installers download `tools/install.sh` or `tools/install.ps1` from GitHub raw content and run locally.",
        "Installing adds managed hook files under `~/.claude/hooks` and updates `~/.claude/settings.json`",
        "it does not upload settings, hook files, shell history, repository contents, or safety summary output.",
        "The isolated first-test path uses a temporary `HOME`",
        "Temporary hook trials still edit Claude Code settings while active",
        "It does not execute the dangerous shell or git commands",
        "Read strict verification as boundary evidence, not as a badge",
        "Verify: not run",
        "0 payload checks",
        "FAIL-OPEN",
        "skipped",
        "PreToolUse",
        "Verify: 0 FAIL-OPEN",
        "payload checks actually run",
        "instead of reinstalling repeatedly to chase an A",
        "They are not a sandbox",
        "start a fresh Claude Code session from the same project root",
        "Pre-update baseline: summary/version captured / not captured / not an update issue",
        "regression from a known baseline or a first verified result",
        "Use `summary/version captured` only when both the old Claude Code version",
        "https://framework.boucle.sh/limitations.json",
        "https://framework.boucle.sh/limitations-feed.xml",
        "https://github.com/Bande-a-Bonnot/Boucle-framework/blob/main/tools/safety-check/QUICKSTART.md",
        "https://github.com/Bande-a-Bonnot/Boucle-framework/blob/main/tools/safety-check/SUPPORT_EXAMPLES.md",
        "That support-summary command downloads `tools/safety-check/check.sh` from",
        "runs locally on the current project and Claude Code",
        "It does not upload settings, hook files, shell history, repository",
        "enforce-hooks: CLAUDE.md rule enforcement for covered tool calls",
        "boucle run --dry-run",
    ],
    repo / "docs" / "recipes.html": [
        "tools/enforce/install.sh | bash",
        "Install boundary: this downloads <code>tools/enforce/install.sh</code> and <code>tools/enforce/enforce-hooks.py</code> from GitHub raw content",
        "It may create <code>CLAUDE.md</code>, install <code>.claude/hooks/enforce-hooks.py</code>",
        "update project <code>.claude/settings.json</code>",
        "It does not upload <code>CLAUDE.md</code>, settings, hook files, shell history, repository contents, or audit output",
        "python3 .claude/hooks/enforce-hooks.py --verify",
        "python3 .claude/hooks/enforce-hooks.py --smoke-test",
        "I want to try the hooks without keeping them installed",
        "borrowed machine, a client repo, a CI runner",
        "tools/install.sh | bash -s -- backup",
        "tools/install.sh | bash -s -- backup list",
        "tools/install.sh | bash -s -- uninstall all",
        "After uninstall, the summary should no longer claim a verified hook boundary.",
        "does not mean the current setup is protected.",
        "run <code>backup list</code> first and inspect before restoring",
        "tools/install.ps1) } uninstall all",
        "tools/install.ps1) } backup list",
        "temporary first test",
        "Network boundary: this downloads <code>tools/safety-check/check.sh</code> from GitHub raw content",
        "It does not upload your Claude Code settings, hook files, shell history, repository contents, or summary output.",
        "Read-only review or audit",
        "python3 /tmp/enforce-hooks.py CLAUDE.md --audit --strict",
        "python3 /tmp/enforce-hooks.py CLAUDE.md --smoke-test --strict",
        "In default write-protect mode it blocks Edit, Write, MultiEdit, NotebookEdit, and modifying Bash commands",
        "Put patterns under a <code>[deny]</code> section when Claude must not read, search, list, or reference those paths at all",
        "I need to leave a PR or incident handoff",
        "I want CI to fail when repo hooks stop blocking",
        "test -f .claude/settings.json",
        'tmp_home="$(mktemp -d)"',
        "SAFETY_CHECK_SKIP_CLAUDE_VERSION=1 HOME=\"$tmp_home\" bash /tmp/safety-check.sh --verify --strict",
        "prevents a self-hosted runner's global Claude Code settings",
        "Do not treat <code>install.sh recommended</code> in CI as proof",
        "it does not prove the checked-out <code>.claude/settings.json</code> or repository hook files protect developers",
        "scripted safety-check checks",
        "Pre-update baseline: summary/version captured / not captured / not an update issue",
        "first verified result for an already-untrusted setup",
        "Fresh Claude Code session started after verification: yes / no",
        "Treat this as a boundary statement, not a certificate.",
        "team handoff reports",
        "tools/install.sh | bash -s -- all <span class=\"prompt-char\">$</span> curl -fsSL https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.sh | bash -s -- verify",
        "start a fresh Claude Code session from the same project root",
        "Command boundary: this downloads <code>tools/safety-check/check.sh</code> from GitHub raw content",
        "does not upload <code>settings.json</code>, hook files, shell history, repository contents, session logs, or safety summary output",
        "The checker does not upload <code>settings.json</code>, hook files, shell history, repository contents, session logs, or safety summary output.",
        "Claude Code updated. Are my hooks still working?",
        "Fix path: back up settings, upgrade, doctor, then strictly verify from the same project root",
        "record <code>claude --version</code> and a <code>--verify --summary-only</code> result",
        "claude --version 2&gt;/dev/null",
        "tools/install.sh | bash -s -- backup",
        "claude --version 2&gt;$null",
        "tools/install.ps1) } backup",
        "backup list",
        "Keep the backup until the fresh session proves the hook boundary still works.",
        "restore settings.20260101_120000.json",
        "safety-check/check.sh | bash -s -- --verify --strict",
        "tools/safety-check/UPDATE_CHECKLIST.md",
        "application/atom+xml",
        "Claude Code Hook Limitations Feed",
        "application/json",
        "Claude Code Hook Limitations JSON",
        "/limitations-feed.xml",
        "/limitations.json",
        "Limitations Feed",
    ],
    repo / "docs" / "limitations.html": [
        "https://framework.boucle.sh/limitations.html",
        "Boucle LLM Summary",
        "type=\"text/plain\"",
        "/llms.txt",
        "Claude Code Hook Limitations Feed",
        "application/json",
        "Claude Code Hook Limitations JSON",
        "limitations-feed.xml",
        "limitations.json",
        "Source data",
        "title=\"Machine-readable JSON",
        "<a href=\"/\">Home</a>",
        "<a href=\"/recipes.html\">Recipes</a>",
        "<a href=\"/llms.txt\">LLM Summary</a>",
        "<a href=\"/limitations-feed.xml\">Limitations Feed</a>",
        "<a href=\"/limitations.json\">JSON</a>",
        "<a href=\"https://github.com/Bande-a-Bonnot/Boucle-framework\">GitHub</a>",
    ],
    repo / "docs" / "recipes.html": [
        "python3 /tmp/enforce-hooks.py CLAUDE.md --verify --strict",
        "tools/safety-check/check.sh | bash -s -- --verify",
        "python3 /tmp/enforce-hooks.py CLAUDE.md --smoke-test --strict",
    ],
}

missing = []
for path, snippets in docs.items():
    flat_text = " ".join(path.read_text().split())
    for snippet in snippets:
        if snippet not in flat_text:
            missing.append(f"{path.relative_to(repo)}: missing {snippet!r}")

if missing:
    raise SystemExit("Hook requirements docs drifted:\n" + "\n".join(missing))

hook_files = sorted((repo / "tools").glob("*/hook.sh"))
jq_hooks = [path for path in hook_files if "jq" in path.read_text()]
expected_count = f"{len(jq_hooks)} of the {len(hook_files)} standalone shell hooks use jq"
if expected_count != "6 of the 7 standalone shell hooks use jq":
    raise SystemExit(
        "Hook jq dependency count changed; update requirements docs and this "
        f"contract together (actual: {expected_count})"
    )

banned = {
    repo / "tools" / "safety-check" / "README.md": [
        "## No dependencies",
        "real test payloads",
    ],
    repo / "tools" / "safety-check" / "check.sh": [
        "No installation, no dependencies",
        "real payloads",
        "live verification (sends `rm -rf /`",
    ],
    repo / "README.md": [
        "cargo test           # Framework tests (",
        "218 Rust tests",
        "Boucle-framework has 96 stars",
        "not yet in the official docs",
        "real payloads",
    ],
    repo / "docs" / "recipes.html": [
        "Blocks Read, Edit, Write, and Bash access to matching paths",
        "installs and verifies the seven standalone <code>.ps1</code> hooks",
    ],
    repo / "tools" / "enforce" / "README.md": [
        "The current docs still describe",
        "The docs still say",
    ],
    repo / "docs" / "index.html": [
        "218 Rust tests",
    ],
    repo / "docs" / "recipes.html": [
        "tools/install.sh | bash -s -- enforce",
    ],
    repo / "tools" / "safety-check" / "CI.md": [
        "repository settings point to native `.ps1` hook scripts, either add PowerShell to the runner",
        "PowerShell installer verification path",
        "shell: pwsh run: | iex \"& { $(irm https://raw.githubusercontent.com/Bande-a-Bonnot/Boucle-framework/main/tools/install.ps1) } verify\"",
    ],
}

violations = []
for path, snippets in banned.items():
    text = path.read_text()
    for snippet in snippets:
        if snippet in text:
            violations.append(f"{path.relative_to(repo)}: remove stale {snippet!r}")

if violations:
    raise SystemExit("Hook requirements docs contain stale wording:\n" + "\n".join(violations))

print("Hook docs requirements OK")
PY
